### ISSUE TITLE
Database Dump From wow query dev

### ISSUE THREAD

**Issue by jdubs1994** [francis-schiavo/blizzard_api#10]
Hey, I couldn't find where else to contact you but I'm trying to unzip the database dump and I'm getting 
gunzip: dump.sql.gz: unexpected end of the file.

It also shows the size of the dump at 0 Kb.

Am I doing something wrong or is the dump contain nothing/bugged. 

I just want to get a dump of the items so I can create an autocomplete search since the blizzard API search is no good.

**Comment by francis-schiavo** [comment]
Indeed there is a problem right now on the database and schema export feature. Unfortunately wow-query.dev is not currently under development while I focus on other projects.
