### ISSUE TITLE
Support for Character profile toys collection

### ISSUE THREAD

**Issue by finnlux** [francis-schiavo/blizzard_api#17]
Are you planning to add support for character toy collections? (/profile/wow/character/:realm/:character/collections/toys)

**Comment by francis-schiavo** [comment]
Sure, I added the toy and  heirloon data endpoints in my last update but I missed the profile endpoints.
I'll add them as son as I can, probably within the next 2 days.

**Comment by finnlux** [comment]
Thanks, I really appreciate it!

**Comment by francis-schiavo** [comment]
Done. Please upgrade to version 3.4.1 and let me know if you find any trouble.

**Comment by finnlux** [comment]
It works! Thanks, now I can continue my work!
